algo = input('Digite Algo:')
print('O tipo primitivo de Algo:', type(algo))
print('Só tem espaços?', algo.isspace())
print('É numérico?', algo.isnumeric())
print('Algo é alfabetico?', algo.isalpha())
print('É alphanumérco?', algo.isalnum())
print('Algo esta em Maiúscula?', algo.isupper())
print('Algo esta em Minúscula?', algo.islower())
print('Está Capitalizada?', algo.istitle())